// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Generated by: WorkerGenerator
// **************************************************************************

dynamic $getMyServiceActivator() => throw UnimplementedError();
