// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Generated by: WorkerGenerator
// **************************************************************************

import 'package:squadron/squadron_service.dart';
import 'my_service.dart';

// Web entry point
void main() => run($MyServiceInitializer, null, ParentSquadronLogger());

dynamic $getMyServiceActivator() => 'example/my_service.web.g.dart.js';
