// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Generated by: WorkerGenerator
// **************************************************************************

import 'package:squadron/squadron_service.dart';
import 'my_service.dart';

// VM entry point
void _start(Map command) =>
    run($MyServiceInitializer, command, ParentSquadronLogger());

dynamic $getMyServiceActivator() => _start;
